// <auto-generated />
using System;
using CourseDataManagement.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CourseDataManagement.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220315124114_v1")]
    partial class v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CourseDataManagement.Models.ExternalModeration", b =>
                {
                    b.Property<string>("CourseID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfExternalmoderatorReport")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfResponseToReport")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatePassedToExternalModerator")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameOfExternalModerator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NextDueDateForExternalModeration")
                        .HasColumnType("datetime2");

                    b.Property<string>("SendEmailNotificationTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseID");

                    b.ToTable("externalModeration");
                });
#pragma warning restore 612, 618
        }
    }
}
